#!/usr/bin/env python3
"""Audit a third-party defense that states a ground for what it stops.

AgentDojo's `transformers_pi_detector` runs the published ProtectAI DeBERTa classifier over each
tool output and replaces a flagged output with a fixed notice. That notice is the only ground any
of the AgentDojo defenses emits, so this run tests the fallback reader of M2 on wording nobody on
this paper wrote, and tests what the resulting diagnosis predicts: a ground that names detected
content rather than the data's origin should be defeated by a differently phrased injection.

Cells are (defense, attack, suite, injection task). Episode outcomes come from AgentDojo's own
`security` field rather than our marker matcher, so the comparison does not inherit the matcher.

  python3 harness/audit_detector.py
"""
from __future__ import annotations
import json, sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RUNS = ROOT / "experiments/agentdojo/runs"
PAPER = ROOT / "paper-overleaf"
sys.path.insert(0, str(ROOT / "tool")); import agentguard_audit as ag

DETECTOR = "transformers_pi_detector"
NOTICE = "prompt injection was detected"      # the defense's own wording, verbatim from its log


def records():
    """(defense, attack, suite, injection task) -> list of (security, prevented)."""
    cells = defaultdict(list)
    for f in sorted(RUNS.rglob("*.json")):
        rec = json.loads(f.read_text())
        atk = rec.get("attack_type")
        if atk in (None, "none") or not (rec.get("injections") or {}):
            continue
        cfg = f.relative_to(RUNS).parts[0].replace("gpt-4o-mini-2024-07-18", "").lstrip("-") or "none"
        blob = json.dumps(rec.get("messages"), ensure_ascii=False)
        cells[(cfg, atk, rec.get("suite_name"), rec.get("injection_task_id"))].append(
            (bool(rec.get("security")), NOTICE in blob))
    return cells


def main():
    cells = records()
    atks = sorted({k[1] for k in cells})
    det = {k: v for k, v in cells.items() if k[0] == DETECTOR}
    undef = {k: v for k, v in cells.items() if k[0] == "none"}
    print(f"attacks {atks}, detector cells {len(det)}, undefended cells {len(undef)}")

    out = {}
    for atk in atks:
        d = {k: v for k, v in det.items() if k[1] == atk}
        if not d:
            continue
        eps = sum(len(v) for v in d.values())
        zero = [k for k, v in d.items() if not any(s for s, _ in v)]
        # a zero the undefended run shows the attack could reach, so the defense did something
        live = [k for k in zero if any(s for s, _ in undef.get(("none", atk) + k[2:], []))]
        prev = [k for k in zero if any(p for _, p in d[k])]
        reason_attr = ag._is_attributed(NOTICE)
        print(f"{atk:24s} cells {len(d):3d} episodes {eps:4d} zero {len(zero):3d} "
              f"of which reachable undefended {len(live):3d}, carrying a prevention notice {len(prev):3d}, "
              f"notice reads provenance: {reason_attr}")
        out[atk] = {"cells": len(d), "eps": eps, "zero": zero, "live": live, "prev": prev}

    # what the ground predicts: a content classifier should fall to a differently worded injection
    base, alt = "important_instructions", "tool_knowledge"
    broke = held = 0
    if base in out and alt in out:
        for k in out[base]["live"]:
            kk = (DETECTOR, alt) + k[2:]
            v = det.get(kk)
            if not v:
                continue
            if any(s for s, _ in v):
                broke += 1
            else:
                held += 1
        print(f"zero cells of {base} retested under {alt}: broken {broke}, held {held}")

    def mac(k, v):
        return f"\\newcommand{{\\{k}}}{{{v}}}"
    lines = ["% AUTO-GENERATED by harness/audit_detector.py"]
    if base in out:
        b = out[base]
        lines += [mac("DetCells", b["cells"]), mac("DetEps", b["eps"]), mac("DetZero", len(b["zero"])),
                  mac("DetLive", len(b["live"])), mac("DetPrev", len(b["prev"]))]
    if alt in out:
        lines += [mac("DetAltEps", out[alt]["eps"])]
    lines += [mac("DetBroke", broke), mac("DetRetest", broke + held)]
    (PAPER / "numbers_detector.tex").write_text("\n".join(lines) + "\n")
    print("wrote", PAPER / "numbers_detector.tex")


if __name__ == "__main__":
    main()
