#!/usr/bin/env python3
"""Reproduction check against the released upstream auditor.

Runs the upstream agentguard-audit (clone path given by --upstream) and the local patched fork
on the SAME result databases, and emits paper-overleaf/numbers_upstream.tex so every number the
paper states about this check comes from a macro.

  python3 harness/upstream_check.py --upstream /tmp/agentguard-upstream
"""
from __future__ import annotations
import argparse, importlib.util, json, os, sqlite3, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "experiments/audit-validity/results"
CAS = ROOT / "experiments/audit-validity/cases"
PAPER = ROOT / "paper-overleaf"
COMPLY = ["gpt-4o-mini-2024-07-18", "gpt-4.1-mini-2025-04-14", "gpt-4.1-nano-2025-04-14", "deepseek-v3.2",
          "doubao-seed-2-0-pro-260215", "deepseek-v3.1-terminus", "doubao-seed-1-8-251228"]
ARMS = ["none", "const", "ifc", "prompt", "partial", "allow", "judge", "capreader"]
SINKS = {"send_email", "create_calendar_event", "post_message"}
REG = {"none": set(), "prompt": set(), "const": SINKS, "ifc": SINKS, "partial": {"send_email"},
       "allow": SINKS, "judge": SINKS, "capreader": SINKS}


def load(path, name):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


def verdict(mod, db, suite, arm):
    cs = mod._load_cases(str(CAS / f"{suite}.jsonl"))
    return mod.compute_metrics(mod.audit_one(db, cs, set(REG[arm])))["completeness"]


def exe_local(v2, model, arm, suite):
    db = RES / f"{suite}__{arm}__{model}.sqlite"
    if not db.exists():
        return None
    cs = v2._load_cases(str(CAS / f"{suite}.jsonl"))
    con = sqlite3.connect(str(db)); n = k = 0
    for cid, ae in con.execute("select case_id, action_events from runs"):
        c = cs.get(cid)
        if not c:
            continue
        n += 1
        if any(v2._ev_hit(v2._keys_of(c), v2._exfil_of(c), e) for e in json.loads(ae or "[]")
               if not e.get("blocked") and not v2._is_mem_write(e)):
            k += 1
    con.close()
    return k / n if n else None


def exe_upstream(up, model, arm, suite):
    """Upstream matching: plain marker substring in executed params, no goal binding, no folding."""
    db = RES / f"{suite}__{arm}__{model}.sqlite"
    if not db.exists():
        return None
    cs = up._load_cases(str(CAS / f"{suite}.jsonl"))
    con = sqlite3.connect(str(db)); n = k = 0
    for cid, ae in con.execute("select case_id, action_events from runs"):
        c = cs.get(cid)
        if not c:
            continue
        n += 1
        keys = up._keys_of(c)
        ok = [e for e in json.loads(ae or "[]") if not e.get("blocked") and not up._is_mem_write(e)]
        blob = json.dumps([e.get("params", {}) for e in ok], ensure_ascii=False)
        if any(kk in blob for kk in keys):
            k += 1
    con.close()
    return k / n if n else None


def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--upstream", required=True); a = ap.parse_args()
    up = load(os.path.join(a.upstream, "agentguard_audit.py"), "upmod")
    v2 = load(str(ROOT / "tool/agentguard_audit.py"), "v2mod")
    commit = os.popen(f"git -C {a.upstream} rev-parse --short=7 HEAD").read().strip()

    agree = differ = 0
    for m in COMPLY:
        for arm in ARMS:
            db = RES / f"S__{arm}__{m}.sqlite"
            if not db.exists():
                continue
            if verdict(up, str(db), "S", arm) == verdict(v2, str(db), "S", arm):
                agree += 1
            else:
                differ += 1

    out = {}
    for arm, su in (("const", "A2"), ("capreader", "A3")):
        for tag, fn in (("Loc", exe_local), ("Up", exe_upstream)):
            mod = v2 if tag == "Loc" else up
            b = t = 0
            for m in COMPLY:
                s0 = fn(mod, m, arm, "S") if tag == "Loc" else fn(mod, m, arm, "S")
                nn = fn(mod, m, "none", "S")
                if s0 == 0 and nn and nn > 0:
                    t += 1
                    b += (fn(mod, m, arm, su) or 0) > 0
            out[arm + tag] = (b, t)

    mac = [f"\\newcommand{{\\UpCommit}}{{{commit}}}",
           f"\\newcommand{{\\UpAgree}}{{{agree}}}",
           f"\\newcommand{{\\UpCells}}{{{agree + differ}}}",
           f"\\newcommand{{\\UpDiffer}}{{{differ}}}"]
    for arm in ("const", "capreader"):
        for tag in ("Loc", "Up"):
            b, t = out[arm + tag]
            key = arm.capitalize() + ("Ours" if tag == "Loc" else "Upstream")
            mac.append(f"\\newcommand{{\\Up{key}Broke}}{{{b}}}")
            mac.append(f"\\newcommand{{\\Up{key}N}}{{{t}}}")
    (PAPER / "numbers_upstream.tex").write_text("% AUTO-GENERATED by harness/upstream_check.py\n" + "\n".join(mac) + "\n")
    print(f"upstream {commit}: verdict agreement {agree}/{agree+differ}, differ {differ}")
    for k, v in out.items():
        print(f"  {k}: {v[0]}/{v[1]}")


if __name__ == "__main__":
    main()
